In [4]:
mealCost = float
tipPercent = int 
taxPercent = int 

In [24]:
def solve(mealCost, tipPercent, taxPercent): 
    totalCost = round( mealCost + \
                      (mealCost*(tipPercent/100)) + \
                      (mealCost*(taxPercent/100)) \
                     )
    return totalCost 

In [25]:
solve(12, 20, 8)

15

In [26]:

if n % 2 != 0: 
    print('Weird')
elif n % 2 == 0 and n <= 5 and n >= 2: 
    print('Not Weird')
elif n % 2 == 0 and n >= 6 and n <= 20: 
    print('Weird')
elif n % 2 == 0 and n > 20: 
    print('Not Weird')
    

In [29]:
n = 22

n_tester(n)

Not Weird greater than 20


In [64]:
# class vs. instance 
 
class Person: 
    def __init__(self, initialAge):
        self.age = 0 
        if initialAge < 0: 
            print('Age is not valid, setting age to 0')
        else: 
            self.age = initialAge
        
    def amiOld(self): 
        if self.age < 13: 
            print('You are young')
        elif self.age >= 13 and self.age < 18: 
            print('You are a teenager')
        else: 
            print('You are old')
                   
    def yearPasses(self):
        self.age == self.age+1
             

In [ ]:
class Person: 
    def __init__(self, initialAge):
        self.age = 0 
        if initialAge < 0: 
            print('Age is not valid, setting age to 0.')
            self.initialAge = self.age 
        else: 
            self.age = initialAge 

    def amIOld(self): 
        if self.age < 13: 
            print('You are young.')
        elif self.age >= 13 and self.age < 18: 
            print('You are a teenager.')
        else: 
            print('You are old.')
                   
    def yearPasses(self):
        self.age += 1
               

t = int(input())
for i in range(0, t):
    age = int(input())         
    p = Person(age)  
    p.amIOld()
    for j in range(0, 3):
        p.yearPasses()       
    p.amIOld()
    print("")

In [76]:
n = int(input())

for i in range(1,11): 
    multiple = n * i 
    print('{} x {} = {}'.format(n, i, multiple)) 

        
printMultiple(n)

n x 1 = 2
n x 2 = 4
n x 3 = 6
n x 4 = 8
n x 5 = 10
n x 6 = 12
n x 7 = 14
n x 8 = 16
n x 9 = 18
n x 10 = 20


In [113]:
s = 'Test String'

#range(100)[5:18:2]
print(s[:6:])
    

Test S


In [106]:
for i in range(int(input())):
    s = input()
    print(s[::2], s[1::2])

2
Python
Pto yhn
Today
Tdy oa


In [32]:
arr = list(map(int, input().rstrip().split()))
print(' things'.join(str(x) for x in arr[::-1]))

12345
12345


In [30]:
arr = list(map(int, input().rstrip().split()))
le_test = ['#'.join([x for x in str(i)]) for i in arr]

1234


In [31]:
print(le_test)

['1#2#3#4']


In [45]:
arr = list(map(int, input().rstrip().split()))
xd = arr.reverse()
le_test = ' '.join([str(i) for i in arr])

1 4 6 8 0


In [52]:
print(arr)
print(xd)
print(le_test)

[4354, 6876876, 22432]
None
4354 6876876 22432


In [53]:
arr = list(map(int, input().rstrip().split()))
xd =arr.reverse()
le_test = ' '.join([str(i) for i in arr])
le_output=' '.join([' '.join([jk for jk in i]) for i in le_test.split(' ')])

9890


In [54]:
print(le_test)
print(le_output)

9890
9 8 9 0


In [55]:
arr = list(map(int, input().rstrip().split()))

to_rev=[xstr for xstr in ('#'.join([str(i) for i in arr]))]
xd =to_rev.reverse()
le_output=' '.join(to_rev)

1234


In [60]:
print(arr)
print(xd)
print(le_output)

[1234]
None
4 3 2 1


In [ ]:
arr = list(map(int, input().rstrip().split()))

In [2]:
phoneBook = []

s = input() 

tel['jack'] = 1234 

{x: x+'='+i for j in ('sape')}
    

sam 99912222


In [ ]:
n = int(input()) 
nn = [input().split() for _ in range(n)]

phoneBook = {} 
phoneBook = dict(nn)

print(phoneBook)

while True: 
    try: 
        name = input() 
        if name in phoneBook: 
            print(name + '=' + phoneBook[name])
        else:
            print('Not found')
    except: 
        break 

1
sam 23235
{'sam': '23235'}
sam
sam=23235


In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
z = int(input()) 

b = [x.split(' ') for x in z[1:z[0]+1:]]
c = [x for x in z[z[0]+1::]]

phoneBook = {} 
phoneBook = dict(b)

for i in c:  
    if phoneBook.get(i) == None: 
        print('Not found')
    else:
        print(i + '=' + phoneBook[i])

In [28]:
print(phoneBook)

{'sam': '1293812', 'tom': '123123', 'jerry': '123123'}


In [ ]:
phoneBook = {} 
phoneBook[x] = y 

phoneBook[key] = value 

In [3]:
print(phoneBook)

['s', 'a', 'm', ' ', '9', '9', '9', '1', '2', '2', '2', '2']


In [ ]:
n = 11 
x = '3 7 8 5 12 14 21 13 18 40 70'
x = list(map(int, x.split())) 

from statistics import median

x = sorted(x)
print(x) 

n2 = n//2 
print(n2)

print(x[:n//2])
print(x[(n+1)//2:])
print(x[6:])

print(int(median(x[:n//2])))
print(int(median(x)))
print(int(median(x[(n+1)//2:])))


# print(percs[0])
# print(percs[1])
# print(percs[2])

ns = [3,4,5,6,7,8,9,10,11,12,13,14,15]

for i in ns: 
    print(i)
    print('middle value is n value divided by 2 is {}'.format(i//2))
    print('middle value is n value +1 divided by 2 is {}'.format((i+1)//2))
    

In [3]:
import collections as cc

zeebus = 'Hello Wrold zoom zoom'

y = cc.Counter(zeebus)

In [4]:
print(y)

Counter({'o': 6, 'l': 3, ' ': 3, 'z': 2, 'm': 2, 'H': 1, 'e': 1, 'W': 1, 'r': 1, 'd': 1})


In [157]:
import numpy as np 

x = np.array([1,2,3,4,5,6,7,7,6,5,4,4,3])
y = np.bincount(x)


In [158]:
print(y)
set(x)

[0 1 1 2 3 2 2 2]


{1, 2, 3, 4, 5, 6, 7}

In [159]:
z = list(zip(x,y))
print(z)

[(1, 0), (2, 1), (3, 1), (4, 2), (5, 3), (6, 2), (7, 2), (7, 2)]


In [167]:
unzip = zip(*z)
print(list(unzip))

[(1, 2, 3, 4, 5, 6, 7, 7), (0, 1, 1, 2, 3, 2, 2, 2)]


In [152]:
#z = np.array(z)
unnest = [] 

for x in z: 
    for i in x: 
        unnest.append(i)

In [153]:
unnest

[1, 0, 2, 1, 3, 1, 4, 2, 5, 3, 6, 2, 7, 2, 7, 2]

In [160]:
zarray = np.array(z).flatten()

In [161]:
zarray

array([1, 0, 2, 1, 3, 1, 4, 2, 5, 3, 6, 2, 7, 2, 7, 2], dtype=int64)

In [126]:
np.array(unnest).reshape(4,4)

array([[1, 0, 2, 1],
       [3, 1, 4, 2],
       [5, 3, 6, 2],
       [7, 2, 7, 2]], dtype=int64)

In [20]:
dictionarytest = {'a':1, 'b':2, 'c':3}

def someFunction(a, b, c):
    print(a+b+c)
    print(c)
    return 

6
3


In [21]:
someFunction(**dictionarytest)

6
3


In [30]:
numbers = [4,6,7,7,4,4,8,3,4,5]

#evens = [x for x in numbers if x % 2 is 0]

evens = [] 

for x in numbers:
    if x % 2 == 0: 
        evens.append(x)
                     
odds = [x for x in numbers if x % 2 != 0] 
        

In [ ]:
APPLY row/column 
mapapply DF elementwise  
"map" series elementwise 

In [28]:
evens

[4, 6, 4, 4, 8, 4]

In [31]:
odds

[7, 7, 3, 5]

In [32]:
thislist = ['asdf', 'asdf23']
lengths = [len(x) for x in thislist]

In [33]:
lengths

[4, 6]

In [72]:
numbersbig = [] 

for i in range(0,10): 
    numbersbig.append(numbers)

print(numbersbig)
df_num.head()

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]


0  1  2  3  4
0  1  2  3  4  5
1  1  2  3  4  5
2  1  2  3  4  5
3  1  2  3  4  5
4  1  2  3  4  5

In [67]:
df_num = pd.DataFrame(data=numbersbig)
df_num.head()

f = lambda x: float(x)
g = lambda x: '%.2f' % x 

df_num.applymap(g)

0    1    2    3    4
0  1.0  2.0  3.0  4.0  5.0
1  1.0  2.0  3.0  4.0  5.0
2  1.0  2.0  3.0  4.0  5.0
3  1.0  2.0  3.0  4.0  5.0
4  1.0  2.0  3.0  4.0  5.0
5  1.0  2.0  3.0  4.0  5.0
6  1.0  2.0  3.0  4.0  5.0
7  1.0  2.0  3.0  4.0  5.0
8  1.0  2.0  3.0  4.0  5.0
9  1.0  2.0  3.0  4.0  5.0

In [88]:
df_num.iloc[[1,2,3,4],[2,3,4]]

2  3  4
1  3  4  5
2  3  4  5
3  3  4  5
4  3  4  5

In [46]:
import pandas as pd
df_num = pd.DataFrame(data=numbers)

In [71]:
df_num[4].map(g)

0    5.00
1    5.00
2    5.00
3    5.00
4    5.00
5    5.00
6    5.00
7    5.00
8    5.00
9    5.00
Name: 4, dtype: object

In [91]:
df_num[[1,2]]

1  2
0  2  3
1  2  3
2  2  3
3  2  3
4  2  3
5  2  3
6  2  3
7  2  3
8  2  3
9  2  3

In [42]:
df_num.apply(f)

0    3
dtype: int64

In [45]:
numbers = [1,2,3,4,5]
more_numbers = [*numbers, 12,3,5,123]

print(more_numbers)
print(*more_numbers)

[1, 2, 3, 4, 5, 12, 3, 5, 123]
1 2 3 4 5 12 3 5 123


In [43]:
df_num

0
0  4
1  6
2  7
3  7
4  4
5  4
6  8
7  3
8  4
9  5

In [92]:
import uuid

In [94]:
user_id = uuid.uuid1()

In [95]:
print(user_id)

afbe251a-ea13-11e9-8128-484d7ee5a273


In [6]:
# Jumping on Clouds 

n = 7
nn = '0 0 1 0 0 1 0' 

# minimum number of jumps 1 or 2 steps 

In [7]:
c = nn.split()

In [8]:
def jumpingOnClouds(c):
    steps = 0  
    current = 0

    while current < n:
        
        if current+2 == n-1:
            steps += 1 
            break
            
        elif current+1 == n-1:
            steps += 1 
            break 
            
        else: 
            if c[current+2] == '1': 
                current = current+1 
            elif c[current+2] == '0':
                current = current+2
        steps += 1 
        
    return(steps)


In [9]:
jumpingOnClouds(c)

4

In [1]:
# P(x; u) = (e ** -u)(u**x)/x!

from math import e

def factor(num):
    fact = 1
    if num != 0:
        for i in range(1, num + 1):
            fact *= i
    return fact

def poi_dist(avg_success, actual_success):
    prob_k_success = (avg_success ** actual_success * e**(-avg_success)) / factor(actual_success)
    
    return prob_k_success 

round(poi_dist(2.5, 5), 3) 


In [14]:
# Poisson distribution  

# Machine type A or type B 

# number of repairs X that machine A needs is u = 0.88 
### daily cost of operation of A is C_A = 160 + 40X**2 

# number of repairs Y that machine B needs is u = 1.55 
### daily cost of operation is C_B = 128 + 40Y**2 

#poi_dist(0.88, 1)

poi_dist(1.55, 1)

#print(expected_dailycost_A)
#print(expected_dailycost_B)


0.32898435943145177

In [22]:
CA = 160 + 40*(0.88 + 0.88**2)
CB = 128 + 40*(1.55 + 1.55**2) 

print(CA)
print(CB)

226.176
286.1


In [26]:
## Normal Distribution I 

# time to assemble car is X 
# normally distributed with u = 20 and sd = 2 

# 1. probability car can be assembled < 19.5 hours 
# 2. probability car can be assembled between 20-22 hours 

#Z = X - u / sd 

-0.25


In [40]:
import scipy.stats as st 

Z1 = (19.5 - 20)/2 
Z2a = (20-20)/2
Z2b = (22-20)/2

z1_cdf = st.norm.cdf(Z1)
print(round(z1_cdf,3))
z2_cdf = abs(st.norm.cdf(Z2a)-st.norm.cdf(Z2b))
print(round(z2_cdf, 3)) 


0.401
0.341
